config/routes.rb
Dogoodapp::Application.routes.draw do
  resources :authentications

  get "api/index"

  resources :favorites

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :goods

  get "home/index"

  
  match 'add_my_favorites/:good_id' => 'favorites#add_my_favorite', :as => 'add_my_favorite'
  
  match 'inspired_me/:parent_id' => 'goods#inspired_me', :as => 'inspired_me'
  
  match '/auth/:provider/callback' => 'authentications#create'
    
  root :to => "home#index"
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :good
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # GET /favorites
  # GET /favorites.xml
  def index
    @favs = Favorite.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @favorites }
    end
  end

  # GET /favorites/1
  # GET /favorites/1.xml
  def show
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @favorite }
    end
  end

  # GET /favorites/new
  # GET /favorites/new.xml
  def new
    @favorite = Favorite.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @favorite }
    end
  end

  # GET /favorites/1/edit
  def edit
    @favorite = Favorite.find(params[:id])
  end

  # POST /favorites
  # POST /favorites.xml
  def create
    @favorite = Favorite.new(params[:favorite])

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to(@favorite, :notice => 'Favorite was successfully created.') }
        format.xml  { render :xml => @favorite, :status => :created, :location => @favorite }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /favorites/1
  # PUT /favorites/1.xml
  def update
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      if @favorite.update_attributes(params[:favorite])
        format.html { redirect_to(@favorite, :notice => 'Favorite was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.xml
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to(favorites_url) }
      format.xml  { head :ok }
    end
  end
  
  def add_my_favorite    
      favorites = Favorite.where(:good_id => params[:good_id], :user_id => current_user.id)
      
      go = true
        
      # check if favorite exists
    if favorites.count > 0
      go = false
    end
    
    # check if this is the current user
    if Good.find(params[:good_id]).user.id == current_user.id
      go = false
    end
    
    if go == true
      f = Favorite.new
      f.user_id = current_user.id
      f.good_id = params[:good_id]
      f.save
    end
    
    respond_to do |format|
      format.html { redirect_to(goods_path) }
    end
    
  end
  
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :good_id %><br />
    <%= f.text_field :good_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= #render 'form' %>

<%= #link_to 'Show', @favorite %> |
<%= #link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<h1>Listing Your Favorites</h1>
<!-- begin the goods -->
<div class="goods">
  
  <% @favs.each do |fav| %>
  <% good = fav.good %>
  <!-- begin good -->
    <div class="good">
      <div class="deed">
        <div class="desc"><%= good.desc %></div>
        <div class="meta"><em><%= good.created_at.strftime("posted %B %d, %Y at %I:%M %p") %> GMT</em></div>
      </div>
      <div class="actions">
        <div>
          You've favorited this, <%= link_to 'unfavorite?', fav, :confirm => 'Are you sure?', :method => :delete %>
        </div>
        <div>
          Has this deed <%= link_to "inspired you?", inspired_me_path(good) %>
        </div>
        <% if good.parent_id != nil %>
          <div>
            Inspired by <%= link_to "this deed.", good_path(good.parent_id) %>
          </div>
        <% end %>
      </div>
    </div>
  <!-- end good -->
  <% end %>
  
  <div class="clear"></div>
</div>
<% if @favs.empty? %>
  <p>You don't have any favorites, <%= link_to "go check out good deeds others have done", goods_path %></p>
<% end %>
<!-- end the goods -->

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= #render 'form' %>

<%= #link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Good:</b>
  <%= @favorite.good_id %>
</p>

<p>
  <b>User:</b>
  <%= @favorite.user_id %>
</p>


<%= #link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= #link_to 'Back', favorites_path %>