config/routes.rb
Dogoodapp::Application.routes.draw do
  resources :authentications

  get "api/index"

  resources :favorites

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :goods

  get "home/index"

  
  match 'add_my_favorites/:good_id' => 'favorites#add_my_favorite', :as => 'add_my_favorite'
  
  match 'inspired_me/:parent_id' => 'goods#inspired_me', :as => 'inspired_me'
  
  match '/auth/:provider/callback' => 'authentications#create'
    
  root :to => "home#index"
end

app/models/good.rb
class Good < ActiveRecord::Base
  belongs_to :user
  belongs_to :good
  has_many :goods
  has_many :favorites
  
  named_scope :posted_before, lambda { |time_ago| { :conditions => ['created_at   < ?', time_ago] } }
  named_scope :posted_within, lambda { |time_ago| { :conditions => ['created_at   > ?', time_ago] } }
    
  validates :user_id, :presence => true, :length => { :minimum => 1 }
  validates :desc, :presence => true, :length => { :maximum => 120 }
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  # GET /goods
  # GET /goods.xml
  def index
    @goods = Good.order("created_at DESC").all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @goods }
    end
  end

  # GET /goods/1
  # GET /goods/1.xml
  def show
    @good = Good.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @good }
    end
  end

  # GET /goods/inspired_me
  # GET /goods/inspired_me.xml
  def inspired_me
    @good = Good.new
    @parent = Good.find(params[:parent_id])
    
    respond_to do |format|
      format.html
      format.xml { render :xml => @good }
    end
  end
  
  # GET /goods/new
  # GET /goods/new.xml
  def new
    @good = Good.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @good }
    end
  end

  # GET /goods/1/edit
  def edit
    @good = Good.find(params[:id])
  end

  # POST /goods
  # POST /goods.xml
  def create
    @good = Good.new(params[:good])

    respond_to do |format|
      if @good.save
        format.html { redirect_to(goods_path, :notice => 'Good was successfully created.') }
        format.xml  { render :xml => @good, :status => :created, :location => @good }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @good.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /goods/1
  # PUT /goods/1.xml
  def update
    @good = Good.find(params[:id])

    respond_to do |format|
      if @good.update_attributes(params[:good])
        format.html { redirect_to(goods_path, :notice => 'Good was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @good.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.xml
  def destroy
    @good = Good.find(params[:id])
    @good.destroy

    respond_to do |format|
      format.html { redirect_to(goods_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_form.html.erb
<%= form_for(@good) do |f| %>
  <% if @good.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good.errors.count, "error") %> prohibited this good from being saved:</h2>

      <ul>
      <% @good.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc, "Description of your good deed, maximum of 120 characters" %><br />
    <%= f.text_area :desc, :id => 'description' %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit "Record Good Deed", :class => 'btn' %>
  </div>
<% end %>

app/views/goods/edit.html.erb
<h1>Edit your good deed</h1>

<%= render 'form' %>

<%= link_to 'Back', goods_path %>

app/views/goods/index.html.erb
<!-- begin the goods -->
<div class="goods">
  
  <% @goods.each do |good| %>
  <!-- begin good -->
    <div class="good">
      <div class="deed">
        <div class="desc"><%= good.desc %></div>
        <div class="meta"><em><%= good.created_at.strftime("posted %B %d, %Y at %I:%M %p") %> GMT</em></div>
      </div>
      <div class="actions">
        <div>
          So far <%= Favorite.where(:good_id => good).count %> ppl have 
          <% if user_signed_in? and current_user.id != good.user.id %>
            <%= link_to 'favorited', add_my_favorite_path(good) %>
          <% else %>
            favorited
          <% end %>        
          this.
        </div>
        <div>
          This deed has inspired <%= pluralize(Good.where(:parent_id => good.id).count, "good deed") %>, has it <%= link_to "inspired you?", inspired_me_path(good) %>
        </div>
        <% if good.parent_id != nil %>
          <div>
            Inspired by <%= link_to "this deed.", good_path(good.parent_id) %>
          </div>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <% if current_user.id == good.user.id %>
          <div class="myactions">
            <%= link_to 'Edit Deed', edit_good_path(good) %>
            <%= link_to 'Delete Deed', good, :confirm => 'Are you sure?', :method => :delete %>
          </div>        
        <% end %>
      <% end %>
    </div>
  <!-- end good -->
  <% end %>
  
  <div class="clear"></div>
</div>
<!-- end the goods -->

app/views/goods/inspired_me.html.erb
<h1>Tell us about the good deed that you were inspired to do</h1>

<p>You were inspired by <%= link_to "this deed.", good_path(@parent) %></p>

<%= form_for(@good) do |f| %>
  <% if @good.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good.errors.count, "error") %> prohibited this good from being saved:</h2>

      <ul>
      <% @good.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc, "Description of your good deed, maximum of 120 characters" %><br />
    <%= f.text_area :desc, :id => 'description' %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :parent_id, :value => @parent.id %>
  <div class="actions">
    <%= f.submit "Record Good Deed", :class => 'btn' %>
  </div>
<% end %>

<%= link_to 'Back', goods_path %>

app/views/goods/new.html.erb
<h1>Tell us about a good deed that you did today</h1>

<p>Need inspiration? <%= link_to 'Check out good deeds others have done', goods_path %></p>

<%= render 'form' %>

<%= link_to 'Back', goods_path %>

app/views/goods/show.html.erb
<!-- begin the goods -->
<div class="goods">
  
  <!-- begin good -->
    <div class="good">
      <div class="deed">
        <div class="desc"><%= @good.desc %></div>
        <div class="meta"><em><%= @good.created_at.strftime("posted %B %d, %Y at %I:%M %p") %> GMT</em></div>
      </div>
      <div class="actions">
        <div>
          So far <%= Favorite.where(:good_id => @good).count %> ppl have 
          <% if user_signed_in? and current_user.id != @good.user.id %>
            <%= link_to 'favorited', add_my_favorite_path(@good) %>
          <% else %>
            favorited
          <% end %>        
          this.
        </div>
        <div>
          This deed has inspired <%= pluralize(Good.where(:parent_id => @good.id).count, "good deed") %>, has it <%= link_to "inspired you?", inspired_me_path(@good) %>
        </div>
        <% if @good.parent_id != nil %>
          <div>
            Inspired by <%= link_to "this deed.", good_path(@good.parent_id) %>
          </div>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <% if current_user.id == @good.user.id %>
          <div class="myactions">
            <%= link_to 'Edit Deed', edit_good_path(@good) %>
            <%= link_to 'Delete Deed', @good, :confirm => 'Are you sure?', :method => :delete %>
          </div>        
        <% end %>
      <% end %>
    </div>
  <!-- end good -->
  
  <div class="clear"></div>
</div>
<!-- end the goods -->