config/routes.rb
Dogoodapp::Application.routes.draw do
  resources :authentications

  get "api/index"

  resources :favorites

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :goods

  get "home/index"

  
  match 'add_my_favorites/:good_id' => 'favorites#add_my_favorite', :as => 'add_my_favorite'
  
  match 'inspired_me/:parent_id' => 'goods#inspired_me', :as => 'inspired_me'
  
  match '/auth/:provider/callback' => 'authentications#create'
    
  root :to => "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="google-site-verification" content="8JgIoe2Wlzq38XhsQPoYQG_O4wyy7CqcInDvM1v8-x8" />
  <title>Do Good</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-9846072-8']);
    _gaq.push(['_trackPageview']);
  
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  
  </script>
</head>
<body>
  <div id="header">
    <div class="actions">      
      <% if user_signed_in? %>
        <span>Click here to </span><strong><%= link_to "Do Good", new_good_path %></strong> /
        <%= link_to "Good deeds others have done", goods_path %> /
        <%= link_to "Favorites", favorites_path %> /
        <%= link_to "Settings", edit_user_registration_path %>  /  
        <%= link_to "Log Out", destroy_user_session_path %>       
      <% else %>
        <span>Start </span><strong><%= link_to "Doing Good", new_user_session_path %></strong> /
        <%= link_to "Good deeds others have done", goods_path %> /
        <%= link_to "Sign In", new_user_session_path %> /
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
      
    </div>
    <div class="stats">
      <span>
        <em>
          <% todaysthings = Good.posted_within 24.hours.ago %>
          <%= todaysthings.count %>
        </em> good deeds done today, 
        <em><%= Good.all.count %></em> good deeds done so far, 
        <em><%= User.all.count %></em> do gooders
      </span>
    </div>
  </div>
  <div id="content">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</body>
</html>